const fs = require('fs')
const path = require('path')

const projectDir = path.resolve(__dirname, '..', 'Project')
const headFile = path.join(projectDir, 'html', 'head.html')
const initOut = path.join(projectDir, 'Script', 'main', 'module-init.js')

const head = fs.readFileSync(headFile, 'utf-8')
const scriptMatches = [...head.matchAll(/src="(Script\/[^"]+)"/g)]
const scriptPaths = scriptMatches.map((m) => m[1])
const userScripts = scriptPaths.filter((p) => !p.startsWith('Script/vs/'))

// Generate module-init.js
const imports = userScripts.map((p) => {
	const relative = path.relative(
		path.dirname(initOut),
		path.resolve(projectDir, p)
	)
	const normalized = relative.replace(/\\/g, '/')
	return `import '${normalized.startsWith('.') ? normalized : './' + normalized}'`
})
fs.writeFileSync(
	initOut,
	`// Auto-generated by scripts/build-module.js\n// Imports all modules in dependency order (from head.html)\n\n${imports.join('\n')}\n`,
	'utf-8'
)
console.log(
	`[build-module] ✓ Generated module-init.js (${userScripts.length} imports)`
)

let modifiedCount = 0
let exportCount = 0
let requireFixCount = 0

for (const relPath of userScripts) {
	const fullPath = path.resolve(projectDir, relPath)
	if (!fs.existsSync(fullPath)) {
		console.warn(`[build-module] ⚠ File not found: ${fullPath}`)
		continue
	}

	let content = fs.readFileSync(fullPath, 'utf-8')
	const hadExports =
		/^\s*export\s+(const|var|let|function|class|default)/m.test(content)

	// --- Step 1: add exports + window bindings (if not already done) ---
	let lines = content.split('\n')
	const names = hadExports ? [] : scanTopDeclNames(lines)
	let changed = false

	if (names.length > 0) {
		for (const { lineIdx, pattern, replacement } of names) {
			lines[lineIdx] = lines[lineIdx].replace(pattern, replacement)
		}
		lines.push('')
		for (const { name } of names) {
			lines.push(`window.${name} = ${name}`)
		}
		changed = true
		exportCount += names.length
	}

	// --- Step 2: add bare require() support for modules ---
	if (
		usesBareRequire(content) &&
		!content.includes('__nodeRequire') &&
		!content.includes('const require =')
	) {
		const requireLine =
			'const require = window.__nodeRequire || window.require'
		// Insert right after 'use strict' (or at top if no strict mode)
		let insertAt = 0
		for (let i = 0; i < lines.length; i++) {
			const t = lines[i].trim()
			if (t === "'use strict'" || t === '"use strict"') {
				insertAt = i + 1
				break
			}
		}
		lines.splice(insertAt, 0, requireLine)
		changed = true
		requireFixCount++
	}

	if (changed) {
		content = lines.join('\n')
		fs.writeFileSync(fullPath, content, 'utf-8')
		modifiedCount++
		const msg = []
		if (names.length) msg.push(`${names.length} export(s)`)
		if (requireFixCount > 0 && changed && content.includes('__nodeRequire'))
			msg.push('require fix')
		console.log(`[build-module] ✓ ${msg.join(' + ')} → ${relPath}`)
	}
}

console.log(
	`[build-module] ✓ Done. Modified ${modifiedCount} files, added ${exportCount} exports, fixed ${requireFixCount} require() calls.`
)

function usesBareRequire(content) {
	return /\brequire\s*\(/.test(content)
}

function scanTopDeclNames(lines) {
	const results = []
	let braceDepth = 0

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i]
		const trimmed = line.trim()

		const depthBefore = braceDepth
		for (const ch of line) {
			if (ch === '{') braceDepth++
			else if (ch === '}') braceDepth--
		}

		if (depthBefore !== 0) continue

		if (
			trimmed.startsWith('//') ||
			trimmed.startsWith('/*') ||
			trimmed.startsWith('*') ||
			trimmed === '' ||
			trimmed.startsWith('}')
		)
			continue

		const varMatchEq = trimmed.match(/^(const|let|var)\s+([\w$]+)\s*=\s*/)
		if (
			varMatchEq &&
			!trimmed.match(/^(const|let|var)\s*\{/) &&
			varMatchEq[2] !== 'require'
		) {
			const escName = varMatchEq[2].replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
			results.push({
				lineIdx: i,
				name: varMatchEq[2],
				pattern: new RegExp(
					`^(${varMatchEq[1]})\\s+${escName}\\s*=\\s*`
				),
				replacement: `export ${varMatchEq[1]} ${varMatchEq[2]} = `
			})
			continue
		}

		const varMatchNoEq = trimmed.match(
			/^(const|let|var)\s+([\w$]+)\s*(;|\/\/.*)?$/
		)
		if (
			varMatchNoEq &&
			!trimmed.match(/^(const|let|var)\s*\{/) &&
			varMatchNoEq[2] !== 'require'
		) {
			const escName = varMatchNoEq[2].replace(
				/[.*+?^${}()|[\]\\]/g,
				'\\$&'
			)
			results.push({
				lineIdx: i,
				name: varMatchNoEq[2],
				pattern: new RegExp(
					`^(${varMatchNoEq[1]})\\s+${escName}\\s*(;|\/\/.*)?$`
				),
				replacement: `export ${varMatchNoEq[1]} ${varMatchNoEq[2]}`
			})
			continue
		}

		const funcMatch = trimmed.match(/^function\s+([\w$]+)\s*\(/)
		if (funcMatch) {
			results.push({
				lineIdx: i,
				name: funcMatch[1],
				pattern: /^function\s+/,
				replacement: 'export function '
			})
			continue
		}

		const classMatch = trimmed.match(/^class\s+([\w$]+)/)
		if (classMatch) {
			results.push({
				lineIdx: i,
				name: classMatch[1],
				pattern: /^class\s+/,
				replacement: 'export class '
			})
		}
	}

	return results
}
